---
title: "Regression"
output: html_document
date: "2022-09-22"
---

## Package

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(zoo)
library(dplyr)
library(ggplot2) 
library(maps)
library(sp)
library(maptools)
library(geosphere)
library(MASS)
library(viridis) 
```

```{r}
Hurricane_ = read.csv("Hurricane_track/Hurricane_landfall_windspeed.csv", as.is=T)


year <- sub(".*/.*/", "", Hurricane_$year)
month <- sub("/.*", "", Hurricane_$year)
year = substr(year, 1, 4)
Hurricane_$year = as.numeric(year)
Hurricane_$month = as.numeric(month)

Hurricane_$Latitude = as.numeric(substr(Hurricane_$Latitude, 1, 4))
Hurricane_$Longitude = as.numeric(substr(Hurricane_$Longitude, 1, 4))

Hurricane_$Latitude = Hurricane_$Latitude
Hurricane_$Longitude = Hurricane_$Longitude*-1

Hurricane_data_Gulf = Hurricane_[Hurricane_$Longitude < -81.4,]
Hurricane_data_Atlantic = Hurricane_[Hurricane_$Longitude >= -81.4 & Hurricane_$Longitude <= -70 & Hurricane_$Latitude <= 36,]


# Create a base map of the USA
usa_map <- map_data("usa")

# Plot the map with the coordinates
ggplot() +
  geom_polygon(data = usa_map, aes(x = long, y = lat, group = group), fill = "lightgray", color = "black") +
  geom_point(data = Hurricane_data_Gulf, aes(x = Longitude, y = Latitude), color = "purple", size = 1) +
  geom_point(data = Hurricane_data_Atlantic, aes(x = Longitude, y = Latitude), color = "orange", size = 1) +
  coord_fixed(1.3) +  
  labs(title = "Landfall", x = "Longitude", y = "Latitude") +
  xlim(c(-100, -60)) +  
  ylim(c(20, 50)) +     
  theme_minimal()

```

```{r}

#Landfall Distribution
kde_Gulf <- kde2d(Hurricane_data_Gulf$Longitude, Hurricane_data_Gulf$Latitude, n = 500)
kde_Gulf_data <- expand.grid(Longitude = kde_Gulf$x, Latitude = kde_Gulf$y)
kde_Gulf_data$Density <- as.vector(kde_Gulf$z)

kde_Atlantic <- kde2d(Hurricane_data_Atlantic$Longitude, Hurricane_data_Atlantic$Latitude, n = 500)
kde_Atlantic_data <- expand.grid(Longitude = kde_Atlantic$x, Latitude = kde_Atlantic$y)
kde_Atlantic_data$Density <- as.vector(kde_Atlantic$z)


ggplot() +
  geom_polygon(data = usa_map, aes(x = long, y = lat, group = group), fill = "lightgray", color = "black") +
  geom_tile(data = kde_Gulf_data, aes(x = Longitude, y = Latitude, fill = Density)) +
  geom_tile(data = kde_Atlantic_data, aes(x = Longitude, y = Latitude, fill = Density)) +
  geom_contour(data = kde_Gulf_data, aes(x = Longitude, y = Latitude, z = Density)) +
  geom_contour(data = kde_Atlantic_data, aes(x = Longitude, y = Latitude, z = Density)) +
  scale_fill_viridis_c() +  # Optional: Use a color palette for better visuals
  labs(title = "Hurricane Landfall KDE",x = "Longitude",y = "Latitude") +
  coord_fixed(1.3) + 
  xlim(c(-100, -60)) +  
  ylim(c(20, 50)) +  
  theme_minimal()

write.csv(Hurricane_data_Gulf, file = "Data/Hurricane_landfall_Gulf.csv", row.names = FALSE)
write.csv(Hurricane_data_Atlantic, file = "Data/Hurricane_landfall_Atlantic.csv", row.names = FALSE)

```


```{r}
# Month Distribution
counts = table(Hurricane_data_Gulf$month)
percentages = counts/ nrow(Hurricane_data_Gulf)
print("Gulf, month distribution")
percentages

counts = table(Hurricane_data_Atlantic$month)
percentages = counts/ nrow(Hurricane_data_Atlantic)
print("Atlantic, month distribution")
percentages

# SS Distribution
counts = table(Hurricane_data_Gulf$SS)
percentages = counts/ nrow(Hurricane_data_Gulf)
print("Gulf, SS distribution")
percentages

counts = table(Hurricane_data_Atlantic$SS)
percentages = counts/ nrow(Hurricane_data_Atlantic)
print("Atlantic, SS distribution")
percentages

# Frequency Distribution
counts = table(Hurricane_data_Gulf$year)
max_frequency = max(counts)
mean_frequency = sum(counts)/ 173
print("Gulf, max and mean")
max_frequency
mean_frequency

counts = table(Hurricane_data_Atlantic$year)
max_frequency = max(counts)
mean_frequency = sum(counts)/ 173
print("Gulf, max and mean")
max_frequency
mean_frequency
```
```{r}
# Regression
data_all = read.csv("Hurricane_track/Data_all.csv")

data_all$type1[data_all$type1 == 0] = 0.00001
data_all$type2[data_all$type2 == 0] = 0.00001


bc <- boxcox(type1 ~ SVI + node1 + population + SS_scale, data = data_all)
bc$x[which(bc$y == max(bc$y))]

bc <- boxcox(type2 ~ SVI + node1 + population + SS_scale, data = data_all)
bc$x[which(bc$y == max(bc$y))]

model1 = lm(type1^(0.17900578267425277) ~ SVI + node1 + population + SS_scale, data = data_all)
summary(model1)
model2 = lm(type2^(0.1414141) ~ SVI + node1 + population + SS_scale, data = data_all)
summary(model2)
```
```{r}
# Collect socioeconomic Data
#state_id_Gulf = c("TX","LA","MS","AL","FL")
#state_id_Atlantic = c("SC","NC","FL")

state_id_Gulf = c("FL")
state_id_Atlantic = c("FL")

data_path = "Data"

# Location and Population
county_all = read.csv("Data/uscounties.csv")
county_all = county_all[, c("state_id", "county_full", "lng", "lat", "population")]

Data_Gulf = county_all[county_all$state_id %in% state_id_Gulf, ]
Data_Atlantic = county_all[county_all$state_id %in% state_id_Atlantic, ]

# SVI
file_list_Gulf <- lapply(state_id_Gulf, function(state) {read.csv(file.path(data_path, paste0(state, ".csv")))})
SVI_data_Gulf <- do.call(rbind, file_list_Gulf)
SVI_data_Gulf = SVI_data_Gulf[, c("COUNTY", "RPL_THEMES", "ST_ABBR")]
names(SVI_data_Gulf)[names(SVI_data_Gulf) == "COUNTY"] = "county_full"
names(SVI_data_Gulf)[names(SVI_data_Gulf) == "ST_ABBR"] <- "state_id"
names(SVI_data_Gulf)[names(SVI_data_Gulf) == "RPL_THEMES"] <- "SVI"

file_list_Atlantic <- lapply(state_id_Atlantic, function(state) {read.csv(file.path(data_path, paste0(state, ".csv")))})
SVI_data_Atlantic <- do.call(rbind, file_list_Atlantic)
SVI_data_Atlantic = SVI_data_Atlantic[, c("COUNTY", "RPL_THEMES", "ST_ABBR")]
names(SVI_data_Atlantic)[names(SVI_data_Atlantic) == "COUNTY"] <- "county_full"
names(SVI_data_Atlantic)[names(SVI_data_Atlantic) == "ST_ABBR"] <- "state_id"
names(SVI_data_Atlantic)[names(SVI_data_Atlantic) == "RPL_THEMES"] <- "SVI"

```

```{r}
county_HRI_table = read.csv("Data/NRI_Table_Counties.csv")
Gulf_risk_data = county_HRI_table[county_HRI_table$STATEABBRV %in% state_id_Gulf, ]
Atlantic_risk_data = county_HRI_table[county_HRI_table$STATEABBRV %in% state_id_Atlantic, ]

Gulf_risk_data = Gulf_risk_data[Gulf_risk_data$HRCN_HLRR %in% c('Very High', 'Relatively High'), ]
Atlantic_risk_data = Atlantic_risk_data[Atlantic_risk_data$HRCN_HLRR %in% c('Very High', 'Relatively High'), ]

Gulf_risk_data = Gulf_risk_data[,c("STATEABBRV","COUNTY","COUNTYTYPE","HRCN_HLRR")]
Gulf_risk_data$county_full = paste(Gulf_risk_data$COUNTY, Gulf_risk_data$COUNTYTYPE)
Gulf_risk_data <- Gulf_risk_data %>%rename(state_id = STATEABBRV)

Atlantic_risk_data = Atlantic_risk_data[,c("STATEABBRV","COUNTY","COUNTYTYPE","HRCN_HLRR")]
Atlantic_risk_data$county_full = paste(Atlantic_risk_data$COUNTY, Atlantic_risk_data$COUNTYTYPE)
Atlantic_risk_data <- Atlantic_risk_data %>%rename(state_id = STATEABBRV)

```



```{r}
# Combine Location and Population with SVI

Data_Atlantic = inner_join(Data_Atlantic, SVI_data_Atlantic, by = c("county_full", "state_id"))
Data_Gulf = inner_join(Data_Gulf, SVI_data_Gulf, by = c("county_full", "state_id"))

Gulf_df = merge(Data_Gulf, Gulf_risk_data, by = c("county_full", "state_id"))
Atlantic_df = merge(Data_Atlantic, Atlantic_risk_data, by = c("county_full", "state_id"))


write.csv(Atlantic_df, file = "Data/Data_Atlantic.csv", row.names = FALSE)
write.csv(Gulf_df, file = "Data/Data_Gulf.csv", row.names = FALSE)

```

